### ISSUE TITLE
xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by yfangZhang** [IBM/Grapher#19]
Traceback (most recent call last):
  File "/public/home/jsj_duanpf/zhyifang/llm4kg/Grapher/main.py", line 170, in <module>
    main(args)
  File "/public/home/jsj_duanpf/zhyifang/llm4kg/Grapher/main.py", line 40, in main
    dm.prepare_data()
  File "/public/home/jsj_duanpf/zhyifang/llm4kg/Grapher/data/dataset.py", line 100, in prepare_data
    self.prepareWebNLG()
  File "/public/home/jsj_duanpf/zhyifang/llm4kg/Grapher/data/dataset.py", line 59, in prepareWebNLG
    b.fill_benchmark(files)
  File "/public/home/jsj_duanpf/zhyifang/llm4kg/Grapher/corpusreader/benchmark_reader.py", line 144, in fill_benchmark
    tree = Et.parse(myfile)
  File "/public/home/jsj_duanpf/miniconda3/envs/grapher/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/public/home/jsj_duanpf/miniconda3/envs/grapher/lib/python3.9/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by imelnyk** [comment]
Hi,
It might be some incorrectly formed string which throws an arrow. Check your input.
